Dockerfile, OWNERS, entrypoint.sh, manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
This ports the build part from OKD release periodics into a separate repo.
TODO:
https://github.com/openshift/machine-config-operator/pull/2181
machine-api could not communicate to AWS endpoints. Seems OVS is conflicting with systemd-resolved, so it needs to be disabled on the hosts
=> Add initial machine-os-content for OKD 4.7

Dockerfile, OWNERS, entrypoint.sh, manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
This ports the build part from OKD release periodics into a separate repo.
Currently FCOS default resolver - `systemd-resolved` needs to be disabled as it seems to break CoreDNS resolution
=> [release-4.6] Add initial machine-os-content for OKD 4.6

entrypoint.sh, overlay/etc/NetworkManager/conf.d/dns.conf, overlay/etc/systemd/system/coreos-migrate-to-systemd-resolved.service.d/disabled.conf, overlay/etc/systemd/system/systemd-resolved.service.d/disabled.conf, overlay/usr/lib/tmpfiles.d/etc.conf
This PR includes:
* #8 - This replaces `echo -n` way to create files on host
* Remove additional refs (FCOS version tag) which confuses bootstrap (it expects a single ref)
* Avoid creating /etc/resolv.conf symlink to systemd-resolved managed file
Related to https://github.com/openshift/okd/issues/380
=> [release-4.6] Fix invalid symlink on second boot

entrypoint.sh
Use cri-o 1.19 in 4.7 to align with k8s 1.19.
Related: https://github.com/openshift/okd/issues/341
=> Use CRI-O 1.19

overlay/etc/nsswitch.conf
systemd-resolved seems to break mDNS plugin used in oVirt/vSphere installs.
Instead of
> hosts:      files resolve [!UNAVAIL=return] myhostname dns
we should be using
> hosts: files dns myhostname
(as in F32).
Ref: https://github.com/openshift/okd/issues/401
=> overlay: add custom /etc/nsswitch.conf

Dockerfile, bootstrap/manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, bootstrap/manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml, bootstrap/manifests/99-okd-community-operators.yaml, bootstrap/manifests/99-okd-master-disable-mitigations.yaml, bootstrap/manifests/99-okd-worker-disable-mitigations.yaml, bootstrap/overlay/etc/pivot/kernel-args, bootstrap/overlay/etc/systemd/system/openshift-gcp-routes.service, bootstrap/overlay/etc/zincati/config.d/90-disable-feature.toml, bootstrap/overlay/usr/local/bin/openshift-gcp-routes.sh
This adds a new 'bootstrap' folder, which would do the following:
* append "manifests" to the assets
* place "overlay" files on bootstrap before pivot
Using this schema we could allow us centralize all config files we use for OKD and make installer delta smaller.
Tested with https://github.com/vrutkovs/installer/commits/fcos-4.7-devel - installer fork now no longer container OKD-specific manifests.
OS extensions in `manifests/` and `bootstrap/manifests` are currently intentionally duplicated:
* fresh installs would use extensions from bootstrap/manifests, created by installer
* 4.5 -> 4.6 upgrades would have OS extensions setup injected by MCO.
So once we don't need any 4.5 -> 4.6 edges we could remove manifests/ from the image.
=> Add files to be reused by installer

entrypoint.sh
These two RPMs are supported in RHCOS, and the MCO e2e tests check
whether they are available.
OKD should also provide the ability to extend the OS with them,
although not install them by default.
=> Add usbguard and kernel-devel RPMs to extensions yum repo

overlay/etc/systemd/system/gcp-hostname.service
Currently this service starts on any install types. We should be running it on GCP only to prevent it from failing on AWS/baremetal etc. and confusing users.
Ref: https://github.com/openshift/okd/issues/396
=> overlay: run gcp-hostname on GCP only

entrypoint.sh
Built using the following procedure:
* Boot into FCOS next
* Run 
```
rpm-ostree update \
--install glusterfs \
--install glusterfs-fuse \
--install open-vm-tools \
--install NetworkManager-ovs \
--install usbguard
--install kernel-devel
```
rpm-ostree would output a list of added dependencies RPMs required to
install these RPMs
=> Update a list of vendored RPMs

bootstrap/overlay/etc/systemd/system/multi-user.target.wants/openshift-gcp-routes.service, bootstrap/overlay/etc/systemd/system/multi-user.target.wants/vmtoolsd.service, entrypoint.sh
This ensures vmtoolsd would be started on bootstrap nodes for vSphere installs.
=> bootstrap: install open-vm-tools binaries from RPMs

Dockerfile
Recent cosa:latest image seems to set invalid selinux labels so kubelet 
can't access pull secret on bootstrap.
We should be using stable cosa version until the issue is sorted out.
=> Dockerfile: use stable cosa

bootstrap/pre-pivot.sh
This script would run during release-image-download.sh and update the bootstrap node:
* Copy pivot files from `bootstrap/` to add necessary bootstrap node modifications
* Extract MCD from the image and place it to /usr/local/bin/machine-config-daemon
* Prepare image-pullspec
* Run `machine-config-daemon pivot` and reboot
Once this lands I'll update installer fork to run this script instead of amending `release-image-download.sh`
=> bootstrap: add pre-pivot.sh

entrypoint.sh
This package is being installed during MCO tests, along with kernel-devel. Required to pass TestKernelType test in MCO's okd-gcp-op
=> Add kernel-headers to internal repo

entrypoint.sh
See https://github.com/coreos/coreos-assembler/issues/1958
This lets us find the problem cheaply here instead of much
later in cluster CI.
=> Fail the build if kubelet isn't labeled correctly

entrypoint.sh
Latest FCOS breaks the cluster - workers can't join the cluster. Use latest passing build while we investigate.
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/50
https://bugzilla.redhat.com/show_bug.cgi?id=1908527
=> [4.6] Pin FCOS to 33.20201209.10.0

entrypoint.sh
Latest FCOS breaks the cluster - workers can't join the cluster. Use latest passing build while we investigate.
Seems to be caused by https://bugzilla.redhat.com/show_bug.cgi?id=1908527.
GCP promotion has [passed](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/promote-release-openshift-okd-machine-os-content-e2e-gcp-4.7/1339159997140963328), but it later fails on AWS
=> Pin FCOS to 33.20201209.10.0

entrypoint.sh
This reverts commit 2a0fec2c9fc9384e7d51e240475561e8eb9a4a36 and switches FCOS stream to stable.
Fixes https://github.com/openshift/okd/issues/383
=> [4.6] Use FCOS stable stream

entrypoint.sh, overlay/etc/resolv.conf, overlay/etc/systemd/resolved.conf.d/no-dns-stub.conf
After pivot systemd-resolved cannot reset /etc/resolv.conf symlink due to a SELinux issue (https://github.com/coreos/fedora-coreos-tracker/issues/649). `okd-machine-os` should make this link in the custom ostree commit as well.
Related: https://github.com/openshift/okd/issues/440
=> Symlink resolv.conf to /run/systemd/resolve/resolv.conf

overlay/etc/resolv.conf, overlay/etc/systemd/resolved.conf.d/no-dns-stub.conf
After pivot systemd-resolved cannot reset /etc/resolv.conf symlink due to a SELinux issue (https://github.com/coreos/fedora-coreos-tracker/issues/649). Bring back DNSStubListener setting for systemd-resolved.
Cherry-pick of #52 on release-4.6, fixes https://github.com/openshift/okd/issues/440
=> [4.6] Symlink resolv.conf to /run/systemd/resolve/resolv.conf

entrypoint.sh
OKD 4.7 has been updated to use kubernetes 1.20, so CRI-O version
needs to be bumped
=> entrypoint.sh: use crio 1.20

entrypoint.sh
This stable snapshot no longer prevents workers from joining
=> [4.6] Pin to 33.20210104.10.0

overlay/etc/localtime
On boot empty `/etc/localtime` dir is being created, which breaks fluentd.
OKD payload should default to UTC.
Related: https://github.com/openshift/okd/issues/310
=> overlay: symlink /etc/localtime to UTC

bootstrap/overlay/etc/ssh/sshd_config.d/10-insecure-rsa-keysig.conf, overlay/etc/ssh/sshd_config.d/10-insecure-rsa-keysig.conf
In general this is insecure, but its necessary for OKD CI for now.
Master version of #55
=> overlay: support RSA keys

overlay/etc/resolv.conf
This is no longer necessary, as latest FCOS already does that
=> overlay: remove resolv.conf symlink

manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
OKD content layers open-vm-tools and dependencies so that bootstrap node would be visible in vSphere installs. Later on we request this RPM to be installed as well.
This makes `rpm-ostree` race as it may unexpectedly find the existing file.
=> entrypoint: remove open-vm-tools from extension RPMs

entrypoint.sh
4.6 builds should be using stable CRIO
=> [release-4.6] entrypoint.sh: use stable CRIO

bootstrap/manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, bootstrap/manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
`open-vm-tools` RPM is still requested in bootstrap manifests
=> bootstrap: remove open-vm-tools requests

overlay/etc/systemd/system/multi-user.target.wants/vmtoolsd.service, overlay/etc/systemd/system/vmtoolsd.service.requires/vgauthd.service
vSphere tools services should autorun on masters.
Related: https://github.com/openshift/okd/issues/483
=> overlay: start open-vm-tools services

Dockerfile
Reverts openshift/okd-machine-os#81
Invalid kubelet label set: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/promote-release-openshift-okd-machine-os-content-e2e-aws-4.7/1358702467373600768
=> Revert "[release-4.6] Dockerfile: use latest coreos assembler"

Dockerfile
Reverts openshift/okd-machine-os#80
Still breaks kubelet label: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/promote-release-openshift-okd-machine-os-content-e2e-aws-4.7/1358702467373600768
=> Revert "Dockerfile: use latest coreos assembler"

entrypoint.sh
Use published packages built on OBS instead of Fedora's bodhi and
modularity.
Fixes https://github.com/openshift/okd/issues/463
=> [release-4.6] Install CRI-O from OBS

entrypoint.sh
Use published packages built on OBS instead of Fedora's bodhi and 
modularity.
~~This uses older `cri-tools` from Fedora, until its available in OBS.~~
Ref: https://github.com/openshift/okd/issues/463
=> Install CRI-O from OBS

entrypoint.sh
Switch back to "stable" channel and add a matching RPM version until stable commit catches up with NetworkManager update
=> [release-4.6] Switch back to stable, add matching NetworkManager-ovs RPM

entrypoint.sh
OKD 4.7 is now stable so it should be using FCOS stable stream
=> [4.7] Switch to stable FCOS stream

entrypoint.sh
This reverts commit 1f396a5431598ce0cb8ba1d5810ea13f4f855d21.
This was accidentally merged after master started tracking 4.8. Latest master should use `next-devel`
=> Revert "Switch to stable FCOS stream"

entrypoint.sh
OKD 4.7 is now our stable branch, so it should use stable FCOS commits
=> [release-4.7] Switch to stable FCOS stream

entrypoint.sh
This reverts commit d509b35a295410d734aa0bf96857bc8ef238c0e0.
FCOS stable was updated and includes compatible NM
=> [release-4.6] Revert "extensions: fetch NM-ovs version compatible with stable"

manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
Required to make CVO apply these manifests, so that we'd ensure all builds have necessary extensions installed
=> manifests: add include.release annotations

bootstrap/overlay/etc/dhclient/dhclient.conf, overlay/etc/dhclient/dhclient.conf
This should resolve odd br-ex behaviour we're seeing with new NMs
=> [release-4.6] overlay: add dhcp-client-identifier

bootstrap/overlay/etc/dhclient/dhclient.conf, overlay/etc/dhclient/dhclient.conf
This should resolve odd br-ex behaviour we're seeing with new NMs
=> [release-4.7] overlay: add dhcp-client-identifier

bootstrap/overlay/etc/dhclient/dhclient.conf, overlay/etc/dhclient/dhclient.conf
This should resolve odd br-ex behaviour we're seeing with new NMs
=> overlay: add dhcp-client-identifier

Dockerfile
Accidentally set to 4.7 during previous cherrypicks
=> Dockerfile: use 4.8 inputs

entrypoint.sh
This should fix machine-os-content after FCOS `next-devel` moved to F34
=> Add liburing for extension RPMs, use F33 CRI-O

Dockerfile, entrypoint.sh
This ensures RPMs are fetched without xattrs, as rpm-ostree 2020.2 no longer accepts those
=> [release-4.7] Strip xattrs

Dockerfile, entrypoint.sh
This ensures RPMs are fetched without xattrs, as rpm-ostree 2020.2 no longer accepts those.
Ref: https://github.com/openshift/okd/issues/566#issuecomment-802147697
=> Strip xattrs from RPM before unpacking

entrypoint.sh
4.8 has been rebased on k8s 1.21, use crio 1.21
=> entrypoint: use crio 1.21

entrypoint.sh
FCOS stable may have older packages, no longer available in fedora-update. Look those up in fedora-update-archives
=> Pin NetworkManager-ovs

entrypoint.sh
FCOS stable may have older packages, no longer available in fedora-update. Look those up in fedora-update-archives.
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/120 in release-4.6
=> [release-4.6] Pin NM-ovs, fetch it from fedora-update-archives

entrypoint.sh
Matches latest stable from https://github.com/coreos/fedora-coreos-config/commit/3a7d25aeb696383fff54c47d0b845babf8caa9a4
=> Bump NM to NetworkManager-ovs-1:1.26.8

entrypoint.sh, manifest-lock.x86_64.json
Prevent selinux-policy 34.9 from being installed, as it breaks crio
=> Pin selinux-policy and avoid updating lock-files

overlay.d/99okd/etc/systemd/resolved.conf.d/okd-no-dns-stub.conf
overlay: make sure we explicitely disable DNS Stub Listener
FCOS may reverse it decision landing dns stub, but its should be independent of OKD. Ensure that this config setting is set.
Ref: https://github.com/openshift/okd/issues/690
=> Set DNS stub listener

manifests/99-master-okd-extensions.yaml, manifests/99-worker-okd-extensions.yaml
OKD no longer requires OS extensions to run and includes them in the base image. This would ensure 99-master/worker-okd-extensions MCs no longer list those
=> Unset os extensions in OKD machine configs

overlay.d/99okd/etc/systemd/resolved.conf.d/okd-no-dns-stub.conf
FCOS may reverse it decision landing dns stub, but its should be independent of OKD. Ensure that this config setting is set.
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/140
=> [release-4.7] overlay: make sure we explicitely disable DNS Stub Listener

Dockerfile.template, entrypoint.sh
Use `createrepo` util in cosa container to have `/extensions` created as a valid repo, as MCD requires that when os extensions are installed
=> Dockerfiles: /extensions needs to be a valid RPM repo

manifests/99-master-okd-extensions.yaml, manifests/99-worker-okd-extensions.yaml
OKD no longer requires OS extensions to run and includes them in the base image. This would ensure 99-master/worker-okd-extensions MCs no longer list those
=> [release-4.7] manifests: unset OKD extensions

Dockerfile.template, entrypoint.sh
Use `createrepo` util in cosa container to have `/extensions` created as a valid repo, as MCD requires that when os extensions are installed
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/143 on release-4.7
=> [release-4.7] Dockerfiles: /extensions needs to be a valid RPM repo

manifests/99-worker-okd-extensions.yaml
Fix a typo in 99-worker-okd-extensions name
=> manifests: fix a typo in worker extensions list

manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml
This ensures the manifests are being synced by CVO.
Cherry-pick of #154 on `release-4.7`. Fixes https://github.com/openshift/okd/issues/710
=> [release-4.7] manifests: add CVO annotations

overlay.d/99okd/usr/lib/systemd/system-preset/00-okd.preset, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-search.service
…ll/17201
This was introduced inn Fedora 34 systemd-248.3-1.fc34.
This breaks internal DNS resolution in the OKD cluster.
Signed-off-by: John Fortin <fortinj66@gmail.com>.
Resubmitted https://github.com/openshift/okd-machine-os/pull/158 to pass build system limitations
=> Undo systemd-resolved change in https://github.com/systemd/systemd/pull/17201

fedora-updates-archive.repo, manifest-lock.overrides.yaml, manifest.yaml
Update to latest stable Fedora CoreOS config, update NetworkManager and pin `selinux-policy`
=> [release-4.7] Bump fedora-coreos-config

overlay.d/99okd/usr/lib/systemd/system-preset/00-okd.preset, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-search.service
This is required for machines to report valid IP on oVirt
=> overlay: ensure machines have qemu-guest-agent enabled

manifests/99-master-okd-extensions.yaml, manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml, manifests/99-worker-okd-extensions.yaml
Other installer components are using 3.2.0
=> bootstrap manifests: update Ignition version

manifests/99-master-okd-extensions.yaml, manifests/99-okd-community-operators.yaml, manifests/99-worker-okd-extensions.yaml
Make sure all manifests have necessary annotations. Cherry-pick of #176 on release-4.8
=> [release-4.8] bootstrap/manifests: set CVO annotations

Dockerfile.cosa
=> Bug 2000584: Use 4.9 MCD and artifacts

manifest-lock.overrides.yaml
Current NM build has been pruned, newer NM 1.32 builds require updated glibc, blocked by selinux pin
=> overrides: remove NM override

manifest-lock.overrides.yaml
Current NM build has been pruned, newer NM 1.32 builds require updated glibc, blocked by selinux pin
=> [release-4.8] overrides: remove NM override

overlay.d/99okd/etc/systemd/network/98-ovs-mac.link
Replaces the dhclient config overlay.
Restores openshift#108 (which fixes openshift/okd#540)
Co-Authored-By: Christian Glombek <13365531+LorbusChris@users.noreply.github.com>
=> [release-4.7] overlay: add NetworkManager config to prevent requesting additional MAC

overlay.d/99okd/etc/systemd/network/98-ovs-mac.link
Replaces the dhclient config overlay.
Restores openshift#108 (which fixes openshift/okd#540)
Co-Authored-By: Christian Glombek <13365531+LorbusChris@users.noreply.github.com>
=> [release-4.8] overlay: add NetworkManager config to prevent requesting additional MAC

overlay.d/99okd/etc/systemd/network/98-ovs-mac.link
Replaces the dhclient config overlay.
Restores openshift#108 (which fixes openshift/okd#540)
Co-Authored-By: Christian Glombek <13365531+LorbusChris@users.noreply.github.com>
=> overlay: add NetworkManager config to prevent requesting additional MAC

bootstrap/overlay/etc/systemd/system/zincati.service.d/okd-machine-os-disabled.conf
Restore dropin conf for disabling Zincati, that was unintentionally removed in https://github.com/openshift/okd-machine-os/pull/117
Reported in https://github.com/openshift/okd/issues/898
Backport of https://github.com/openshift/okd-machine-os/pull/202
=> [release-4.8] overlay: Disable zincati.service via dropin on bootstrap node

bootstrap/overlay/etc/systemd/system/zincati.service.d/okd-machine-os-disabled.conf
Restore dropin conf for disabling Zincati, that was unintentionally removed in https://github.com/openshift/okd-machine-os/pull/117
Reported in https://github.com/openshift/okd/issues/898
=> overlay: Disable zincati.service via dropin on bootstrap node

.github/dependabot.yaml, bootstrap/overlay/etc/pivot/kernel-args, manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml
Use cgroupsv2 for new installs and updated clusters.
Also fixes a typo in dependabot config
=> Enable cgroupsv2 for OKD 4.10

manifest-lock.overrides.yaml
Sync manifest-lock.overrides too
=> [release-4.7] Bump fedora-coreos-config to latest stable

manifest-lock.overrides.yaml
Sync manifest-lock.overrides.yaml
=> [release-4.8] Bump fedora-coreos-config to latest stable

manifest-lock.overrides.yaml
Sync manifest-lock.overrides.yaml
=> [release-4.9] Bump fedora-coreos-config to latest stable

manifest-lock.overrides.yaml
Sync manifest-lock overrides. This should bring in 1.22.2 kubelet
=> [release-4.9] Update fedora-coreos-config to latest stable Nov 9

manifest-lock.overrides.yaml
=> [release-4.7] Update Fedora CoreOS stable

manifest-lock.overrides.yaml
=> [release-4.8] Update Fedora CoreOS config to latest stable

.github/dependabot.yml
Remove dependabot config to trigger a new build
=> [release-4.7] Remove .github, dependabot doesn't work for non-default branches

manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml
CVO should not be tracking this file, so that users could modify it enabling cgroupsv2 mode when required
=> [release-4.9] kernel arguments: don't track kernel-args

crio.repo
Use https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable:cri-o:1.23 as source of cri-o packages
Alternative to #274, which we won't have to pass through Bodhi process
=> crio.repo: switch to cri-o 1.23

Dockerfile.template, manifest-lock.overrides.yaml
This should pull in `polkit-0.117-3.fc34.2.x86_64` for https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4034
=> [release-4.9] Dockerfile.template: bump machine-os version

.github/dependabot.yaml
Daily PRs to bump FCOS in master branch are too frequent, resetting this to weekly
=> dependabot: create new PRs weekly

crio.repo
cri-tools was updated to 1.23 and builds on F35
=> crio: use F35 build of cri-tools

crio.repo
cri-tools was updated to 1.23 and builds on F35
Cherry-pick of #313 on release-4.10
=> [release-4.10] crio: use F35 build of cri-tools

Dockerfile.template
Pull in fresh Fedora/CRI-O updates.
Fixes https://github.com/openshift/okd/issues/1156
=> [release-4.10] Bump machine-os version

manifests/99-sca-disable.yaml
This disables SCA setting for Insights Operator to prevent SCA alert.
Fixes https://github.com/openshift/okd/issues/1135
=> manifests: add support secret

manifests/99-sca-disable.yaml
This disables SCA setting for Insights Operator to prevent SCA alert.
Fixes https://github.com/openshift/okd/issues/1135
Cherry-pick of #321 on release-4.10
=> [release-4.10] manifests: add support secret

overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-search.service
Ensure that resolv.conf search domain patching runs after NM has built a new resolv.conf. This should prevent coredns from picking up stub resolver.
Cherry-pick of #323 on release-4.10 branch
Fixes https://github.com/openshift/okd/issues/978
=> [release-4.10] fix-resolv-conf-search.service: run after NM

overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-search.service
Fixes https://github.com/openshift/okd/issues/978
Ensure that resolv.conf search domain patching runs after NM has built a new resolv.conf. This should prevent coredns from picking up stub resolver
=> fix-resolv-conf-search.service: run after NM

overlay.d/99okd/usr/lib/systemd/system/ovsdb-server.service.d/99-okd-permission-fix.conf
Make sure openvswitch configs and run dirs are owned by OVS user.
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/334 on release-4.10
=> [release-4.10] okd overlay: fix openvswitch permissions

overlay.d/99okd/usr/lib/systemd/system/ovsdb-server.service.d/99-okd-permission-fix.conf
Make sure openvswitch configs and run dirs are owned by OVS user. We can't place the dropin in `/etc/systemd` as [it is being cleaned up in post-process](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/ignition-and-ostree.yaml#L45)
Hopefully that fixes https://github.com/openshift/okd/issues/1168.
Mirrored as `quay.io/vrutkovs/okd-release:4.11-apr-4-pr334-v2`
Upgrade jobs:
* [aws](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1511080234059829248)
* [gcp](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-installer-launch-aws-modern/1511084057058873344)
* [aws no disruption tests](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/release-openshift-origin-insta …
=> okd overlay: fix openvswitch permissions

overlay.d/99okd/etc/dhclient/dhclient.conf, overlay.d/99okd/usr/lib/NetworkManager/conf.d/20-dhcp-client-id-mac.conf
This change removes the `/etc/dhclient/dhclient.conf` file that
has been unused since the deprecation of dhclient in Fedora from
the `99okd` overlay, and replaces it with a NetworkManager config
snippet for configuring NM's DHCP client to use
`ipv4.dhcp-client-id=mac`.
See also:
- https://fedoraproject.org/wiki/Changes/dhclient_deprecation
- https://bugzilla.redhat.com/show_bug.cgi?id=1204226
/cc @vrutkovs
=> Configure DHCP client identifier via NM

overlay.d/99okd/etc/dhclient/dhclient.conf, overlay.d/99okd/usr/lib/NetworkManager/conf.d/20-dhcp-client-id-mac.conf
This change removes the `/etc/dhclient/dhclient.conf` file that
has been unused since the deprecation of dhclient in Fedora from
the `99okd` overlay, and replaces it with a NetworkManager config
snippet for configuring NM's DHCP client to use
`ipv4.dhcp-client-id=mac`.
See also:
- https://fedoraproject.org/wiki/Changes/dhclient_deprecation
- https://bugzilla.redhat.com/show_bug.cgi?id=1204226
Cherry-pick of #338 on release-4.10
=> [release-4.10] Configure DHCP client identifier via NM

overlay.d/99okd/usr/lib/systemd/system-preset/00-okd.preset, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-coredns.service, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-dot.service
/etc/resolv.conf copy.
Both are dependent on systemd-resolved but need to be run after
network-online.target to ensure systemd-resolved and NetworkManager have
finished initializing.
make fix-resolv-conf-coredns.service dependent on fix-resolv-conf-dot.service in case there is a dot.
Replaces https://github.com/openshift/okd-machine-os/pull/344 as we need to use repo branches for CI
=> Seperate the two fixes for the 'dot' in /etc/resolv.conf and the coredns

overlay.d/99okd/usr/lib/systemd/system-preset/00-okd.preset, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-coredns.service, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-dot.service
/etc/resolv.conf copy.
Both are dependent on systemd-resolved but need to be run after
network-online.target to ensure systemd-resolved and NetworkManager have
finished initializing.
make fix-resolv-conf-coredns.service dependent on fix-resolv-conf-dot.service in case there is a dot.
cherry-pick of https://github.com/openshift/okd-machine-os/pull/349 on release-4.10
=> [release-4.10] Seperate the two fixes for the 'dot' in /etc/resolv.conf and the coredns

Dockerfile.template, manifest-lock.overrides.yaml
[Kernel regression](https://bugzilla.redhat.com/show_bug.cgi?id=2063929) related to CephFS has been fixed in 5.17.9, which should be available in updates
=> [release-4.10] Unpin kernel

Dockerfile.template
These are required for GCP machines to be able to contact each other
=> Dockerfile: make sure gcp-routes and gcp-hostname services are enabled

Dockerfile.template
Pack hyperkube/crio RPMs and MCD binary in `okd-rpms` image. This image is used by assisted-installer in discovery ISO.
okd-machine-os uses this image to overlay necessary binaries
=> Dockerfile: extract RPMs from `okd-rpms`

Dockerfile, coreos-continuous.repo
Fresh `rpm-ostree` from this COPR should fix https://issues.redhat.com/browse/OKD-63
=> OKD-63: Use CoreOS Continuous copr packages

Dockerfile
I'm not entirely sure if F37 lands in FCOS Stable before 4.12 release, but lets at least have it tested.
Hopefully this will fix https://issues.redhat.com/browse/OKD-62
=> Switch to Fedora CoreOS 37 next

Dockerfile
We no longer run `rpm-ostree update <new machine-os>` so repos should be enabled as these are required to install additional packages.
Fixes #445
=> Dockerfile: no need to disable repos

Dockerfile, overrides.yaml
This works around https://github.com/coreos/rpm-ostree/issues/4037
=> Use `ex rebuild` to pull from COPR

Dockerfile
This is no longer necessary with the new-format base image model and in fact is an anti-pattern because it inhibits running the container directly, which is a valid use case:
```
$ podman run --rm -ti registry.ci.openshift.org/origin/4.12:fedora-coreos
```
should give me a bash shell, not an error.
=> build: Drop `ENTRYPOINT` override

Dockerfile
It should work again now that we've bumped ostree-ext in rpm-ostree with 2022.13.111.g5824de97-1
We do need to remove the `/var/lib/unbound` key because `ostree container commit` flags it as an error now.
=> build: Use `ostree container commit` again

Dockerfile.ci
Update Dockerfile.ci to use the same base image as Dockerfile so that FEDORA_COREOS_VERSION would be correct
=> Dockerfile.ci: fetch version from next-devel

overlay.d/05rhcos
This should apply RHCOS changes, selinux policy upgrade in particular.
Unlike [4.11 cherrypick](https://github.com/openshift/okd-machine-os/pull/451) we're applying the whole overlay - there's plenty of time in the cycle to work out the quirks
Ref: https://github.com/okd-project/okd/issues/1317
=> overlay: add 05rhcos

manifest-lock.overrides.yaml
Bump to latest fedora-coreos and openshift-os. This should also pick up 1.24.6 kubelet
Ref: https://github.com/okd-project/okd/issues/1310
=> [release-4.11] Bump fedora-coreos-config to latest stable

Dockerfile
This PR refers okd-project/okd-payload-pipeline#15
It should be considered a temporary fix to remove when the solutions for the hyperkube, cli and artifacts builds in both okd-payload-pipeline and the current ci converge.
Let's also consider the removal of the /tmp/rpms content. If we want to keep it, I can split the commit or the PR
/cc @vrutkovs @LorbusChris
=> Temporary fix to take the rpms in the correct folder from both prow and the okd-payload-pipeline

crio.repo, manifest.yaml, okd-packages.yaml
This reverts commit 67025f3d40d34fe171611fb23fad054e049f9cf7.
Reverting #249 as now cri-o module lags behind in F36 and it affects OKD 4.11, as predicted in https://github.com/openshift/okd-machine-os/pull/249#issuecomment-1149794989
=> [release-4.11] Revert "manifest: Use cri-o module from Fedora"

Dockerfile
Due to [OKD-62](https://issues.redhat.com//browse/OKD-62) the kernel is pinned to 5.18. This commits removes pin to use latest available
=> Dockerfile: remove kernel pin

Dockerfile.rpms
Create image references file, so that okd-rpms image would be included in the resulting payload.
Later `okd-rpms` image would be used by Assisted Installer to automatically overlay crio and kubelet on FCOS so that discovery agent could start bootstrap.service
=> OKD-90: Add okd-rpms in the payload

bootstrap/pre-pivot.sh
Run script with "eux" bash flags. This also shows status of `registries.conf`
Required to debug https://github.com/openshift/installer/pull/6487
=> pre-pivot: show verbose info

bootstrap/pre-pivot.sh
This updates OKD OS image name to use "fedora-coreos" instead of deprecated "machine-os-content"
=> pre-pivot: fetch "fedora-coreos" image

bootstrap/pre-pivot.sh
This makes sure rpm-ostreed can read registries.conf file so that rpm-ostree rebase via OCI containers
=> pre-pivot: change registries.conf permission

bootstrap/pre-pivot.sh
This makes sure rpm-ostreed can read registries.conf file so that rpm-ostree rebase via OCI containers
=> [release 4.12] pre-pivot: change registries.conf permission

Dockerfile, Dockerfile.ci
This PR will let the fedora-coreos and machine-os-content images built for OKD 4.12 base from quay.io/fedora/fedora-coreos:stable.
/cc @vrutkovs
=> Base the 4.12 okd's fedora-coreos and machine-os-content images from fedora-coreos:stable

Dockerfile, overrides.yaml
OKD 4.12 is now stable and should not override rpm-ostree with testing version from COPR
=> [release-4.12] Dockerfile: remove rpm-ostree override

Dockerfile, Dockerfile.rpms, crio.repo, okd-copr.repo
Use official CRI-O packages from OBS in OKD 4.12
=> Dockerfile.rpms: use stable CRIO releases

overlay.d/99okd/etc/NetworkManager/conf.d/99-okd-dns.conf
With on-prem install NM will create /var/run/NetworkManager/resolv.conf
with connection nameservers. This file is used by keepalived and
coredns to determine connection DNS server and avoid hitting CoreDNS.
On recent F37 NM points to systemd-resolved's stub endpoint. This
setting will prevent it from doing that.
This should fix https://github.com/okd-project/okd/issues/1476
=> overlay: prevent NM from modifying resolv.conf

okd-copr.repo
This fixes Assisted Installer overlay hack:
```
Feb 02 10:29:22 okd-master-0 okd-binaries.sh[1593]: warning: /tmp/rpms/cri-o-1.25.1-None.fc36.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4c5461c: NOKEY
Feb 02 10:29:22 okd-master-0 okd-binaries.sh[1593]: error: Failed dependencies:
Feb 02 10:29:22 okd-master-0 okd-binaries.sh[1593]:         libc.so.6(GLIBC_2.32)(64bit) is needed by cri-o-0:1.25.1-None.fc36.x86_64                                                         
Feb 02 10:29:22 okd-master-0 okd-binaries.sh[1593]:         libc.so.6(GLIBC_2.33)(64bit) is needed by cri-o-0:1.25.1-None.fc36.x86_64
Feb 02 10:29:22 okd-master-0 okd-binaries.sh[1593]:         libc.so.6(GLIBC_2.34)(64bit) is needed by cri-o-0:1.25.1-None.fc36.x86_64
Feb 02 10:29:22 okd-master-0 okd-binaries.sh[1593]: …
```
=> okd-copr: use F37 packages

Dockerfile
Instead of enabling particular servies we should use systemd presets. This would make sure fix-resolv services are enabled too.
=> Dockerfile: enable services via systemd presets

Dockerfile
OVS is using `nc` in some ipv6 flows
Ref: https://github.com/okd-project/okd/issues/1523
=> Dockerfile: install netcat

Dockerfile
ovs-configuration.service may require it in IPv6 flows
Cherrypick of https://github.com/openshift/okd-machine-os/pull/536 on release-4.12
Ref: https://github.com/okd-project/okd/issues/1523
=> [release-4.12] Dockerfile: install netcat

Dockerfile
In case RPMs are bringing their own presets or these get copied from elsewhere
Follow-up for https://github.com/openshift/okd-machine-os/pull/535#issuecomment-1441878620
=> Dockerfile: move systemctl preset-all

Dockerfile
Instead of enabling particular servies we should use systemd presets. This would make sure fix-resolv services are enabled too.
Cherry-pick of #535 and #537 on release-4.12
=> [release-4.12] Dockerfile: enable services via systemd presets

Dockerfile
We're pinned to particular FCOS version, but we still need to make sure newer kubelet is being pulled
=> Dockerfile: replace existing kubelet

overlay.d/99okd/usr/lib/okd/selinux-fixes.cil
OVN uses iptables wrapper, which needs to read/write /dev/null
=> selinux fixes: allow iptables wrapper to write to tmpfs

Dockerfile.ci
Dockerfile.ci should save actual FCOS version we're using in Dockerfile until FCOS is tracking stable again
=> Dockerfile.ci: report real FCOS version

Dockerfile, crio.repo
This reverts commit e83e32a1cb3280265d118377d30bf781fdc6d6e9. Updated FCOS needs to be fetched every time we rebuild this image.
This also pins crio to 1.25.1 as 1.25.2 has a regression (https://issues.redhat.com/browse/OCPBUGS-8093) which fails several storage tests
=> [release-4.12] Revert "DEBUG: don't pull in fresh FCOS"

Dockerfile.ci
This reverts commit 65cd146cc6a5edc47e9e7a68ae180a23a7a60b79.
Fetch FCOS version from FCOS image again
=> [release-4.12] Revert "Dockerfile.ci: report real FCOS version"

Dockerfile
Due to rpm-ostree bug binaries which rely on alternatives don't get final binary symlinked. This change would manually symlink nc to netcat
Ref: https://github.com/okd-project/okd/issues/1523
=> Dockerfile: symlink netcat to nc

Dockerfile
Due to rpm-ostree bug binaries which rely on alternatives don't get final binary symlinked. This change would manually symlink nc to netcat
Cherrypick of https://github.com/openshift/okd-machine-os/pull/564 on release-4.12
=> [release-4.12] Dockerfile: symlink netcat to nc

Dockerfile.rpms, crio.repo, okd-copr.repo
Make sure 4.13 nightlies are using stable CRI-O 1.26
=> [release-4.13] Dockerfile: use CRI-O 1.26

Dockerfile, overlay.d/99okd/usr/libexec/rhcos-rebuild-selinux-policy
remove version check from script so that it will run in fcos
=> overlay: update selinux update script from 05rhcos

Dockerfile
Use arch-specific RPMs when `artifacts` contains multiarch RPMs.
Cherry-pick of #462 on release-4.12
Closes #589 #590
=> [release-4.12] Dockerfile: get arch-specific rpms

overlay.d/99okd/usr/lib/okd/selinux-fixes.cil
Some AVC like the following were generated.
```
AVC avc:  denied  { sys_ptrace } for  pid=59993 comm="ip" capability=19  scontext=system_u:system_r:ifconfig_t:s0 tcontext=system_u:system_r:ifconfig_t:s0 tclass=capability permissive=0
```
See okd-project/okd#1611
=> add SELinux policy for `ip` AVCs

manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml
This was added to fix AWS bug, which has been long since resolved.
Ref: https://github.com/okd-project/okd/issues/1614
=> manifests: remove intel_pstate=disable, enforce cgroupsv2

Dockerfile.rpms, crio.repo, okd-copr.repo, overlay.d/99okd/usr/libexec/kubelet-image-credential-provider-plugins/ecr-credential-provider
CRI-O 1.29 is not yet available, but at least 1.28 would be compatible with new kubelet
=> Bump crio to 1.28

Dockerfile, overlay.d/99okd/usr/libexec/kubelet-image-credential-provider-plugins/ecr-credential-provider
Depends on https://github.com/openshift/release/pull/48496
=> OCPBUGS-28548: Install ecr-credential-provider from artifacts instead of stub script
