Dockerfile, entrypoint.sh, overlay/etc/systemd/system/gcp-hostname.service, overlay/etc/systemd/system/network-online.target.wants/gcp-hostname.service
OKD-specific test of openshift/machine-config-operator#2217.
Fixes https://github.com/openshift/okd/issues/352
=> [release-4.6] Run afterburn in gcp-hostname.service

bootstrap/overlay/etc/systemd/system/zincati.service.d/okd-machine-os-disabled.conf, bootstrap/overlay/etc/zincati/config.d/90-disable-feature.toml
Fixes: https://github.com/openshift/okd/issues/215
=> overlay: Disable zincati.service via dropin

bootstrap/manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, bootstrap/manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml, entrypoint.sh, manifests/0000_80_machine-config-operator_05_1_okd-master-extensions.yaml, manifests/0000_80_machine-config-operator_05_2_okd-worker-extensions.yaml
The RPM has been added to RHCOS [1].
[1] https://github.com/openshift/os/pull/451
=> Add qemu-guest-agent RPM to extensions

overlay/etc/systemd/system/network-online.target.wants/vsphere-hostname.service
Ref: https://github.com/openshift/okd/issues/394, https://github.com/openshift/machine-config-operator/pull/2282#issuecomment-738793162
=> overlay: set vSphere hostname fetched from Afterburn

entrypoint.sh
This would ensure we'd enable target Fedora release modules instead of coreos-assembler version.
Previously F32 RPM of CRI-O has been fetched, now we ensure target version RPM is being downloaded
=> entrypoint.sh: rework fetching crio RPMs

entrypoint.sh, overlay/etc/resolv.conf
This reverts commit b66d8acaec38fbe5008d273637600c447261a66f.
Required to debug https://bugzilla.redhat.com/show_bug.cgi?id=1908527
=> Revert "Pin to 33.20210104.10.0"

README.md
Beginning to document the repository to help people, including possible developers, understand how the process of creating the Machine OS works.
=> initial commit of README

entrypoint.sh
Reverts openshift/okd-machine-os#73
Due to a crio bug `/root/.docker/config.json` is not being picked up.
=> Revert "Install CRI-O from OBS"

bootstrap/overlay/etc/dhclient/dhclient.conf, bootstrap/overlay/etc/systemd/network/98-ovs-mac.link, overlay/etc/dhclient/dhclient.conf, overlay/etc/systemd/network/98-ovs-mac.link
=> [release-4.6] overlay: add NetworkManager config to prevent requesting additional MAC 

bootstrap/overlay/etc/dhclient/dhclient.conf, bootstrap/overlay/etc/systemd/network/98-ovs-mac.link, overlay/etc/dhclient/dhclient.conf, overlay/etc/systemd/network/98-ovs-mac.link
=> [release-4.7] overlay: add NetworkManager config to prevent requesting additional MAC

bootstrap/overlay/etc/dhclient/dhclient.conf, bootstrap/overlay/etc/systemd/network/98-ovs-mac.link, overlay/etc/dhclient/dhclient.conf, overlay/etc/systemd/network/98-ovs-mac.link
Resolves https://github.com/openshift/okd/issues/540
=> overlay: add NetworkManager config to prevent requesting additional MAC

Dockerfile.ci
Create missing`./extensions`, so that release config could use Dockerfile.ci
=> Sync Dockerfile.ci

Dockerfile, entrypoint.sh
Keep in sync with latest NM from stable FCOS stream
=> Update NetworkManager-ovs to 1.30

README.md
List all chanegs we apply on top of fedora-coreos-config and describe the build process
=> README.md: update repo structure and build process

manifest-lock.overrides.yaml
Periodic `testing-devel` update
=> Bump fedora-coreos-config

NM-1.32-copr.repo, manifest-lock.overrides.yaml, manifest.yaml
NM 1.32 fixes hostname resolution via reverse DNS
=> manifest: fasttrack NetworkManager 1.32

NM-1.32-copr.repo, manifest-lock.overrides.yaml, manifest.yaml
=> [release-4.7] manifest: fasttrack NetworkManager 1.32

manifest-lock.overrides.yaml, overlay.d/99okd/usr/lib/systemd/system-preset/00-okd.preset, overlay.d/99okd/usr/lib/systemd/system/fix-resolv-conf-search.service
Requires https://github.com/openshift/release/pull/20533 to fix CI
=> [release-4.8] Periodic submodule bump

manifest-lock.overrides.yaml, manifest.yaml
* Bump fcos config to latest in testing-devel
* Update openshift-os to latest master
* Update FCOS pinned packages and NetworkManager
=> Bump fedora-coreos-config to latest testing-devel

manifests/99-master-okd-extensions.yaml, manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml, manifests/99-worker-okd-extensions.yaml
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/174 on release-4.8
=> [release-4.8] bootstrap manifests: update Ignition version

manifests/99-master-okd-extensions.yaml, manifests/99-okd-community-operators.yaml, manifests/99-worker-okd-extensions.yaml
Make sure all manifests have necessary annotations
=> bootstrap/manifests: set CVO annotations

manifest-lock.overrides.yaml
=> [release-4.7] Bump fedora-coreos-config to latest stable

manifest-lock.overrides.yaml
=> [release-4.8] Bump fedora-coreos-config to latest stable

okd-rpms.repo
=> okd-repos: remove failovermethod

manifests/99-okd-master-disable-mitigations.yaml, manifests/99-okd-worker-disable-mitigations.yaml
Cherry-pick of #257 on master branch
=> kernel arguments: don't track kernel-args

Dockerfile.template
Add version label so that we could trigger rebuilds
=> [release-4.7] Dockerfile.template: add machine-os version label

Dockerfile.template
Trigger a new machine-os rebuild
=> [release-4.9] Dockerfile.template: bump machine-os version

Dockerfile.template
=> [release-4.8] Bump machine-os version

Dockerfile.cosa, Dockerfile.template, manifest.yaml
Needs https://github.com/openshift/release/pull/25760 to properly setup promotion rules
=> Update master versions to 4.11

manifest-lock.overrides.yaml, manifest.yaml
=> [release-4.10] Pin Fedora kernel

manifest-lock.overrides.yaml, manifest.yaml
=> Pin Fedora kernel

manifests/99-sca-disable.yaml
Cherry-pick of https://github.com/openshift/okd-machine-os/pull/368 on 4.10
=> [release-4.10] manifests/99-sca-disable.yaml: quote bool value

manifests/99-sca-disable.yaml
See https://github.com/openshift/okd-machine-os/pull/322#issuecomment-1138385025
=> manifests/99-sca-disable.yaml: quote bool value

manifest-lock.overrides.yaml
=> manifest-lock.overrides.yaml: unpin kernel

Dockerfile.template
=> Dockerfile.template: Log some info about build

Dockerfile, Dockerfile.ci
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1171
=> Dockerfile: update base image location

overlay.d/99okd/usr/lib/systemd/system-preset/43-manifest-rhcos.preset, overlay.d/99okd/usr/lib/systemd/system/rhcos-selinux-policy-upgrade.service, overlay.d/99okd/usr/libexec/rhcos-rebuild-selinux-policy
This should apply RHCOS changes, selinux policy upgrade in particular
Ref: https://github.com/okd-project/okd/issues/1317
=> [release-4.11] overlay: add selinux update script from 05rhcos

Dockerfile, Dockerfile.ci
=> Base the master branch's fedora-coreos image from testing-devel

Dockerfile, Dockerfile.rpms
=> Dockerfile: use 4.14 artifacts

Dockerfile, Dockerfile.rpms
Update master branch to use 4.15 images after branching
=> Bump to 4.15

Dockerfile, Dockerfile.rpms
=> [release-4.14] update version strings, use latest master

Dockerfile
Ref: https://github.com/coreos/fedora-coreos-tracker/issues/1601
=> Dockerfile: remove kernel pin

Dockerfile, Dockerfile.rpms, okd-copr.repo
Fixes [#1798](https://github.com/okd-project/okd/issues/1798)
=> [release-4.14] Fix pinned kernel and CRI-O version

Dockerfile, Dockerfile.ci
=> Dockerfile: switch to testing-devel
